/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#5f5b58",
        "secondary": "#645e59",
        "on-background": "#31332c",
        "on-secondary": "#fff7f4",
        "error-dim": "#5c1202",
        "surface": "#fbf9f4",
        "tertiary-fixed": "#6d89fa",
        "outline": "#797c73",
        "surface-tint": "#625d5b",
        "surface-container-highest": "#e2e3d9",
        "on-error": "#fff7f6",
        "error": "#9e422c",
        "inverse-surface": "#0e0e0c",
        "tertiary-fixed-dim": "#607cec",
        "on-tertiary-fixed": "#000000",
        "error-container": "#fe8b70",
        "secondary-dim": "#58524d",
        "primary-dim": "#56514f",
        "inverse-primary": "#ffffff",
        "tertiary-container": "#6d89fa",
        "surface-variant": "#e2e3d9",
        "tertiary-dim": "#2949b7",
        "on-primary": "#fef6f2",
        "on-primary-fixed": "#433e3c",
        "on-secondary-fixed-variant": "#615a56",
        "on-secondary-fixed": "#443e3a",
        "secondary-container": "#eae1da",
        "surface-bright": "#fbf9f4",
        "on-tertiary": "#faf8ff",
        "primary-container": "#e9e1dd",
        "background": "#fbf9f4",
        "surface-container": "#efeee6",
        "surface-dim": "#d9dbcf",
        "surface-container-high": "#e8e9e0",
        "on-primary-container": "#55514e",
        "on-tertiary-container": "#000a36",
        "on-secondary-container": "#57514c",
        "tertiary": "#3856c4",
        "surface-container-low": "#f5f4ed",
        "on-surface-variant": "#5e6058",
        "primary": "#625d5b",
        "on-tertiary-fixed-variant": "#001454",
        "inverse-on-surface": "#9e9d99",
        "outline-variant": "#b1b3a9",
        "on-error-container": "#742410",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#dcd3cd",
        "on-surface": "#31332c",
        "secondary-fixed": "#eae1da",
        "primary-fixed": "#e9e1dd",
        "primary-fixed-dim": "#dad3cf"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Newsreader", "serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
